import 'dart:io';
import 'dart:async';
import 'dart:ui';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
// import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:select_form_field/select_form_field.dart';
import 'package:sipmas/provider/providers.dart';
import 'package:http/http.dart' as http;
import 'package:sipmas/screens/kadin/main_screen_kadin.dart';
import 'package:timeline_tile/timeline_tile.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../api/api.dart';
import '../../decoration/decorations.dart';
import '../../model/models.dart';
import '../../widgets/widgets.dart';
import '../screens.dart';

part 'kadin_home_screen.dart';
part 'kadin_profile_screen.dart';
part 'data_pegawai_screen.dart';
part 'data_surat_screen.dart';
part 'data_berita_screen.dart';
part 'tambah_berita_screen.dart';
part 'update_berita_screen.dart';
part 'tambah_pegawai_screen.dart';
part 'update_pegawai_screen.dart';
part 'update_surat_screen.dart';
part 'update_profile_screen.dart';